const Nepal = [
  {
    province: "Koshi Province",
    districts: [
      {
        name: "Bhojpur",
        municipalities: [
          { name: "Bhojpur Municipality" },
          { name: "Aamchok Rural Municipality" },
          { name: "Arun Rural Municipality" },
          { name: "Hatuwagadhi Rural Municipality" },
          { name: "Pauwadungma Rural Municipality" },
          { name: "Ramprasad Rai Rural Municipality" },
          { name: "Salpasilichho Rural Municipality" },
          { name: "Temkemaiyung Rural Municipality" },
        ],
      },
      {
        name: "Dhankuta",
        municipalities: [
          { name: "Dhankuta Municipality" },
          { name: "Chhathar Jorpati Rural Municipality" },
          { name: "Khalsa Chhintang Sahidbhumi Rural Municipality" },
          { name: "Mahalaxmi Rural Municipality" },
          { name: "Pakhribas Rural Municipality" },
          { name: "Sangurigadhi Rural Municipality" },
        ],
      },
      {
        name: "Ilam",
        municipalities: [
          { name: "Ilam Municipality" },
          { name: "Deumai Municipality" },
          { name: "Mai Municipality" },
          { name: "Mangalbare Municipality" },
          { name: "Chulachuli Rural Municipality" },
          { name: "Fakphokthum Rural Municipality" },
          { name: "Maijogmai Rural Municipality" },
          { name: "Rong Rural Municipality" },
          { name: "Suryodaya Rural Municipality" },
        ],
      },
      {
        name: "Jhapa",
        municipalities: [
          { name: "Arjundhara Municipality" },
          { name: "Bhadrapur Municipality" },
          { name: "Birtamod Municipality" },
          { name: "Damak Municipality" },
          { name: "Gauradaha Municipality" },
          { name: "Gauriganj Municipality" },
          { name: "Kankai Municipality" },
          { name: "Mechinagar Municipality" },
          { name: "Shivasatakshi Municipality" },
          { name: "Bahradashi Rural Municipality" },
          { name: "Buddhashanti Rural Municipality" },
          { name: "Haldibari Rural Municipality" },
          { name: "Jhapa Rural Municipality" },
          { name: "Kamal Rural Municipality" },
          { name: "Kachankawal Rural Municipality" },
        ],
      },
      {
        name: "Khotang",
        municipalities: [
          { name: "Diktel Rupakot Majhuwagadhi Municipality" },
          { name: "Halesi Tuwachung Municipality" },
          { name: "Aiselukharka Rural Municipality" },
          { name: "Barahapokhari Rural Municipality" },
          { name: "Diprung Rural Municipality" },
          { name: "Jantedhunga Rural Municipality" },
          { name: "Kepilasgadhi Rural Municipality" },
          { name: "Khotehang Rural Municipality" },
          { name: "Sakela Rural Municipality" },
          { name: "Rawabesi Rural Municipality" },
        ],
      },
      {
        name: "Morang",
        municipalities: [
          { name: "Biratnagar Sub-Metropolitan City" },
          { name: "Belbari Municipality" },
          { name: "Letang Municipality" },
          { name: "Pathari-Sanischare Municipality" },
          { name: "Rangeli Municipality" },
          { name: "Ratuwamai Municipality" },
          { name: "Sundarharaicha Municipality" },
          { name: "Urlabari Municipality" },
          { name: "Gramthan Rural Municipality" },
          { name: "Jahada Rural Municipality" },
          { name: "Kanepokhari Rural Municipality" },
          { name: "Kerabari Rural Municipality" },
          { name: "Miklajung Rural Municipality" },
        ],
      },
      {
        name: "Okhaldhunga",
        municipalities: [
          { name: "Siddhicharan Municipality" },
          { name: "Champadevi Rural Municipality" },
          { name: "Chishankhugadhi Rural Municipality" },
          { name: "Khijidemba Rural Municipality" },
          { name: "Likhu Rural Municipality" },
          { name: "Manebhanjyang Rural Municipality" },
          { name: "Molung Rural Municipality" },
          { name: "Sunkoshi Rural Municipality" },
        ],
      },
      {
        name: "Panchthar",
        municipalities: [
          { name: "Phidim Municipality" },
          { name: "Falelung Rural Municipality" },
          { name: "Falgunanda Rural Municipality" },
          { name: "Hilihang Rural Municipality" },
          { name: "Kummayak Rural Municipality" },
          { name: "Miklajung Rural Municipality" },
          { name: "Tumbewa Rural Municipality" },
          { name: "Yangwarak Rural Municipality" },
        ],
      },
      {
        name: "Sankhuwasabha",
        municipalities: [
          { name: "Chainpur Municipality" },
          { name: "Khandbari Municipality" },
          { name: "Bhotkhola Rural Municipality" },
          { name: "Chichila Rural Municipality" },
          { name: "Dharmadevi Rural Municipality" },
          { name: "Madi Rural Municipality" },
          { name: "Makalu Rural Municipality" },
          { name: "Panchkhapan Rural Municipality" },
          { name: "Savapokhari Rural Municipality" },
        ],
      },
      {
        name: "Solukhumbu",
        municipalities: [
          { name: "Salleri Municipality" },
          { name: "Khumbu Pasanglhamu Rural Municipality" },
          { name: "Likhupike Rural Municipality" },
          { name: "Mapya Dudhkoshi Rural Municipality" },
          { name: "Nechasalyan Rural Municipality" },
          { name: "Sotang Rural Municipality" },
        ],
      },
      {
        name: "Sunsari",
        municipalities: [
          { name: "Itahari Metropolitan City" },
          { name: "Dharan Sub-Metropolitan City" },
          { name: "Barahachhetra Municipality" },
          { name: "Duhabi Municipality" },
          { name: "Inaruwa Municipality" },
          { name: "Koshi Municipality" },
          { name: "Ramdhuni Municipality" },
          { name: "Barju Rural Municipality" },
          { name: "Bhokraha Narsingh Rural Municipality" },
          { name: "Dewanganj Rural Municipality" },
          { name: "Gadhi Rural Municipality" },
          { name: "Harinagara Rural Municipality" },
        ],
      },
      {
        name: "Taplejung",
        municipalities: [
          { name: "Phungling Municipality" },
          { name: "Aathrai Tribeni Rural Municipality" },
          { name: "Faktanglung Rural Municipality" },
          { name: "Mikkwakhola Rural Municipality" },
          { name: "Meringden Rural Municipality" },
          { name: "Maiwakhola Rural Municipality" },
          { name: "Pathibhara Yangwarak Rural Municipality" },
          { name: "Phaktanglung Rural Municipality" },
          { name: "Sirijangha Rural Municipality" },
        ],
      },
      {
        name: "Terhathum",
        municipalities: [
          { name: "Myanglung Municipality" },
          { name: "Aathrai Rural Municipality" },
          { name: "Chathar Rural Municipality" },
          { name: "Laligurans Rural Municipality" },
          { name: "Menchayam Rural Municipality" },
          { name: "Phedap Rural Municipality" },
        ],
      },
      {
        name: "Udayapur",
        municipalities: [
          { name: "Beltar Basaha Municipality" },
          { name: "Katari Municipality" },
          { name: "Triyuga Municipality" },
          { name: "Chaudandigadhi Municipality" },
          { name: "Rautamai Rural Municipality" },
          { name: "Tapli Rural Municipality" },
          { name: "Udayapurgadhi Rural Municipality" },
        ],
      },
    ],
  },
  {
    province: "Madhesh Pradesh",
    districts: [
      {
        name: "Bara",
        municipalities: [
          { name: "Baragadhi Rural Municipality" },
          { name: "Devaraha Rural Municipality" },
          { name: "Feta Rural Municipality" },
          { name: "Kalaiya Sub-Metropolitan City" },
          { name: "Karaiyamai Rural Municipality" },
          { name: "Kolhabi Municipality" },
          { name: "Mahagadhimai Municipality" },
          { name: "Nijgadh Municipality" },
          { name: "Pacharauta Municipality" },
          { name: "Parwanipur Rural Municipality" },
          { name: "Prasauni Rural Municipality" },
          { name: "Simraungadh Municipality" },
          { name: "Suwarna Rural Municipality" },
        ],
      },
      {
        name: "Dhanusha",
        municipalities: [
          { name: "Bideha Municipality" },
          { name: "Chhireshwarnath Municipality" },
          { name: "Dhanushadham Municipality" },
          { name: "Ganeshman Charnath Municipality" },
          { name: "Hansapur Municipality" },
          { name: "Janakpur Sub-Metropolitan City" },
          { name: "Kamala Municipality" },
          { name: "Mithila Municipality" },
          { name: "Mithila Bihari Municipality" },
          { name: "Sahidnagar Municipality" },
          { name: "Sabaila Municipality" },
          { name: "Bateshwar Rural Municipality" },
          { name: "Dhanauji Rural Municipality" },
          { name: "Lakshminiya Rural Municipality" },
          { name: "Mukhiyapatti Musharniya Rural Municipality" },
          { name: "Nagarain Municipality" },
        ],
      },
      {
        name: "Mahottari",
        municipalities: [
          { name: "Bardibas Municipality" },
          { name: "Bhangaha Municipality" },
          { name: "Gaushala Municipality" },
          { name: "Jaleshwar Municipality" },
          { name: "Loharpatti Municipality" },
          { name: "Manara Shiswa Municipality" },
          { name: "Matihani Municipality" },
          { name: "Ramgopalpur Municipality" },
          { name: "Balwa Municipality" },
          { name: "Ekdanra Rural Municipality" },
          { name: "Mahottari Rural Municipality" },
          { name: "Pipara Rural Municipality" },
          { name: "Sonama Rural Municipality" },
          { name: "Samsi Rural Municipality" },
        ],
      },
      {
        name: "Parsa",
        municipalities: [
          { name: "Bahudarmai Municipality" },
          { name: "Bindabasini Rural Municipality" },
          { name: "Chhipaharmai Rural Municipality" },
          { name: "Dhobini Rural Municipality" },
          { name: "Jagarnathpur Rural Municipality" },
          { name: "Jirabhawani Rural Municipality" },
          { name: "Paterwa Sugauli Rural Municipality" },
          { name: "Parsagadhi Municipality" },
          { name: "Pokhariya Municipality" },
          { name: "Birgunj Metropolitan City" },
          { name: "Sakhuwa Prasauni Rural Municipality" },
          { name: "Thori Rural Municipality" },
        ],
      },
      {
        name: "Rautahat",
        municipalities: [
          { name: "Baudhimai Municipality" },
          { name: "Brindaban Municipality" },
          { name: "Chandrapur Municipality" },
          { name: "Devahi Gonahi Municipality" },
          { name: "Gadhimai Municipality" },
          { name: "Garuda Municipality" },
          { name: "Gaur Municipality" },
          { name: "Gujara Municipality" },
          { name: "Ishnath Municipality" },
          { name: "Katahariya Municipality" },
          { name: "Madhav Narayan Municipality" },
          { name: "Maulapur Municipality" },
          { name: "Paroha Municipality" },
          { name: "Phatuwa Bijaypur Municipality" },
          { name: "Rajdevi Municipality" },
          { name: "Durga Bhagwati Rural Municipality" },
          { name: "Rajpur Rural Municipality" },
          { name: "Yamunamai Rural Municipality" },
        ],
      },
      {
        name: "Saptari",
        municipalities: [
          { name: "Dakneshwori Municipality" },
          { name: "Hanumannagar Kankalini Municipality" },
          { name: "Kanchanrup Municipality" },
          { name: "Rajbiraj Municipality" },
          { name: "Sambhunath Municipality" },
          { name: "Saptakoshi Municipality" },
          { name: "Surunga Municipality" },
          { name: "Tilathi Koiladi Rural Municipality" },
          { name: "Agnisair Krishnasavaran Rural Municipality" },
          { name: "Balan Bihul Rural Municipality" },
          { name: "Bishnupur Rural Municipality" },
          { name: "Chhinnamasta Rural Municipality" },
          { name: "Khadauna Rural Municipality" },
          { name: "Mahadeva Rural Municipality" },
          { name: "Rajgadh Rural Municipality" },
          { name: "Rupani Rural Municipality" },
          { name: "Tirhut Rural Municipality" },
        ],
      },
      {
        name: "Sarlahi",
        municipalities: [
          { name: "Bagmati Municipality" },
          { name: "Barahathwa Municipality" },
          { name: "Chandranagar Rural Municipality" },
          { name: "Chhatra Municipality" },
          { name: "Dhankaul Rural Municipality" },
          { name: "Haripur Municipality" },
          { name: "Hariwan Municipality" },
          { name: "Ishworpur Municipality" },
          { name: "Kabilasi Municipality" },
          { name: "Lalbandi Municipality" },
          { name: "Malangawa Municipality" },
          { name: "Brahmapuri Rural Municipality" },
          { name: "Balara Municipality" },
          { name: "Parsa Rural Municipality" },
          { name: "Ram Nagar Rural Municipality" },
          { name: "Barahathwa Municipality" },
          { name: "Kavre Rural Municipality" },
          { name: "Bagmati Municipality" },
          { name: "Ishwarpur Municipality" },
          { name: "Hariwan Municipality" },
        ],
      },
      {
        name: "Siraha",
        municipalities: [
          { name: "Dhangadhimai Municipality" },
          { name: "Golbazar Municipality" },
          { name: "Karjanha Municipality" },
          { name: "Lahan Municipality" },
          { name: "Mirchaiya Municipality" },
          { name: "Siraha Municipality" },
          { name: "Sukhipur Municipality" },
          { name: "Kalyanpur Municipality" },
          { name: "Arnama Rural Municipality" },
          { name: "Aurahi Rural Municipality" },
          { name: "Bariyarpatti Rural Municipality" },
          { name: "Bishnupur Rural Municipality" },
          { name: "Naraha Rural Municipality" },
          { name: "Nawarajpur Rural Municipality" },
          { name: "Sakhuwanankarkatti Rural Municipality" },
          { name: "Lakshmipur Patari Rural Municipality" },
        ],
      },
    ],
  },
  {
    province: "Bagmati Province",
    districts: [
      {
        name: "Bhaktapur",
        municipalities: [
          { name: "Bhaktapur Municipality" },
          { name: "Changunarayan Municipality" },
          { name: "Madhyapur Thimi Municipality" },
          { name: "Suryabinayak Municipality" },
        ],
      },
      {
        name: "Chitwan",
        municipalities: [
          { name: "Bharatpur Metropolitan City" },
          { name: "Kalika Municipality" },
          { name: "Khairahani Municipality" },
          { name: "Madi Municipality" },
          { name: "Ratnanagar Municipality" },
          { name: "Rapti Municipality" },
          { name: "Ichchhakamana Rural Municipality" },
        ],
      },
      {
        name: "Dhading",
        municipalities: [
          { name: "Dhunibesi Municipality" },
          { name: "Galchhi Rural Municipality" },
          { name: "Gajuri Rural Municipality" },
          { name: "Gangajamuna Rural Municipality" },
          { name: "Jwalamukhi Rural Municipality" },
          { name: "Khaniyabas Rural Municipality" },
          { name: "Netrawati Dabjong Rural Municipality" },
          { name: "Rubi Valley Rural Municipality" },
          { name: "Siddhalek Rural Municipality" },
          { name: "Thakre Rural Municipality" },
          { name: "Tripurasundari Rural Municipality" },
          { name: "Benighat Rorang Rural Municipality" },
          { name: "Nilkantha Municipality" },
        ],
      },
      {
        name: "Dolakha",
        municipalities: [
          { name: "Bhimeshwor Municipality" },
          { name: "Bigu Rural Municipality" },
          { name: "Baiteshwor Rural Municipality" },
          { name: "Gaurishankar Rural Municipality" },
          { name: "Jiri Municipality" },
          { name: "Kalinchowk Rural Municipality" },
          { name: "Melung Rural Municipality" },
          { name: "Shailung Rural Municipality" },
          { name: "Tamaksuh Rural Municipality" },
        ],
      },
      {
        name: "Kathmandu",
        municipalities: [
          { name: "Kathmandu Metropolitan City" },
          { name: "Budhanilkantha Municipality" },
          { name: "Chandragiri Municipality" },
          { name: "Dakshinkali Municipality" },
          { name: "Gokarneshwor Municipality" },
          { name: "Kageshwori Manohara Municipality" },
          { name: "Kirtipur Municipality" },
          { name: "Nagarjun Municipality" },
          { name: "Shankharapur Municipality" },
          { name: "Tarakeshwor Municipality" },
          { name: "Tokha Municipality" },
        ],
      },
      {
        name: "Kavrepalanchok",
        municipalities: [
          { name: "Banepa Municipality" },
          { name: "Bethanchowk Rural Municipality" },
          { name: "Bhumlu Rural Municipality" },
          { name: "Chaurideurali Rural Municipality" },
          { name: "Dhulikhel Municipality" },
          { name: "Khanikhola Rural Municipality" },
          { name: "Mahabharat Rural Municipality" },
          { name: "Mandandeupur Municipality" },
          { name: "Namobuddha Municipality" },
          { name: "Panchkhal Municipality" },
          { name: "Panauti Municipality" },
          { name: "Roshi Rural Municipality" },
          { name: "Temal Rural Municipality" },
        ],
      },
      {
        name: "Lalitpur",
        municipalities: [
          { name: "Lalitpur Metropolitan City" },
          { name: "Godawari Municipality" },
          { name: "Konjyosom Rural Municipality" },
          { name: "Mahankal Rural Municipality" },
          { name: "Bagmati Rural Municipality" },
          { name: "Lalitpur Metropolitan City" },
          { name: "Mahalaxmi Municipality" },
        ],
      },
      {
        name: "Makwanpur",
        municipalities: [
          { name: "Hetauda Sub-Metropolitan City" },
          { name: "Bakaiya Rural Municipality" },
          { name: "Bagmati Rural Municipality" },
          { name: "Bhaise Rural Municipality" },
          { name: "Bhimphedi Rural Municipality" },
          { name: "Chhatiwan Rural Municipality" },
          { name: "Kailash Rural Municipality" },
          { name: "Makawanpurgadhi Rural Municipality" },
          { name: "Manahari Rural Municipality" },
          { name: "Raksirang Rural Municipality" },
          { name: "Thaha Municipality" },
          { name: "Indrasarowar Rural Municipality" },
        ],
      },
      {
        name: "Nuwakot",
        municipalities: [
          { name: "Bidur Municipality" },
          { name: "Belkotgadhi Municipality" },
          { name: "Dupcheshwar Rural Municipality" },
          { name: "Kakani Rural Municipality" },
          { name: "Kispang Rural Municipality" },
          { name: "Likhu Rural Municipality" },
          { name: "Meghauli Rural Municipality" },
          { name: "Panchakanya Rural Municipality" },
          { name: "Suryagadhi Rural Municipality" },
          { name: "Shivapuri Rural Municipality" },
          { name: "Tadi Rural Municipality" },
          { name: "Tarakeshwor Rural Municipality" },
        ],
      },
      {
        name: "Ramechhap",
        municipalities: [
          { name: "Manthali Municipality" },
          { name: "Ramechhap Municipality" },
          { name: "Sunapati Rural Municipality" },
          { name: "Umakunda Rural Municipality" },
          { name: "Doramba Rural Municipality" },
          { name: "Likhu Rural Municipality" },
          { name: "Khandadevi Rural Municipality" },
          { name: "Gokulganga Rural Municipality" },
          { name: "Ramechhap Municipality" },
        ],
      },
      {
        name: "Rasuwa",
        municipalities: [
          { name: "Gosaikunda Rural Municipality" },
          { name: "Naukunda Rural Municipality" },
          { name: "Parbatikunda Rural Municipality" },
          { name: "Uttargaya Rural Municipality" },
          { name: "Amachhodingmo Rural Municipality" },
        ],
      },
      {
        name: "Sindhuli",
        municipalities: [
          { name: "Kamalamai Municipality" },
          { name: "Dudhaul Rural Municipality" },
          { name: "Golanjor Rural Municipality" },
          { name: "Hariharpurgadhi Rural Municipality" },
          { name: "Marin Rural Municipality" },
          { name: "Phikkal Rural Municipality" },
          { name: "Sunkoshi Rural Municipality" },
          { name: "Tinpatan Rural Municipality" },
          { name: "Ghyanglekh Rural Municipality" },
        ],
      },
      {
        name: "Sindhupalchok",
        municipalities: [
          { name: "Chautara Sangachokgadhi Municipality" },
          { name: "Bahrabise Municipality" },
          { name: "Melamchi Municipality" },
          { name: "Panchpokhari Thangpal Rural Municipality" },
          { name: "Indrawati Rural Municipality" },
          { name: "Helambu Rural Municipality" },
          { name: "Lisankhu Pakhar Rural Municipality" },
          { name: "Jugal Rural Municipality" },
          { name: "Balefi Rural Municipality" },
          { name: "Tripurasundari Rural Municipality" },
          { name: "Bhotekoshi Rural Municipality" },
          { name: "Sunkoshi Rural Municipality" },
        ],
      },
    ],
  },
  {
    province: "Gandaki Province",
    districts: [
      {
        name: "Baglung",
        municipalities: [
          { name: "Baglung Municipality" },
          { name: "Dhorpatan Municipality" },
          { name: "Galkot Municipality" },
          { name: "Jaimuni Municipality" },
          { name: "Bareng Rural Municipality" },
          { name: "Khathekhola Rural Municipality" },
          { name: "Nisikhola Rural Municipality" },
          { name: "Tara Khola Rural Municipality" },
          { name: "Taman Khola Rural Municipality" },
        ],
      },
      {
        name: "Gorkha",
        municipalities: [
          { name: "Gorkha Municipality" },
          { name: "Palungtar Municipality" },
          { name: "Sulikot Rural Municipality" },
          { name: "Siranchok Rural Municipality" },
          { name: "Ajirkot Rural Municipality" },
          { name: "Arughat Rural Municipality" },
          { name: "Bhimsenthapa Rural Municipality" },
          { name: "Dharche Rural Municipality" },
          { name: "Chum Nubri Rural Municipality" },
        ],
      },
      {
        name: "Kaski",
        municipalities: [
          { name: "Pokhara Metropolitan City" },
          { name: "Annapurna Rural Municipality" },
          { name: "Machhapuchchhre Rural Municipality" },
          { name: "Madi Rural Municipality" },
          { name: "Rupa Rural Municipality" },
        ],
      },
      {
        name: "Lamjung",
        municipalities: [
          { name: "Besisahar Municipality" },
          { name: "Madhya Nepal Municipality" },
          { name: "Rainas Municipality" },
          { name: "Sundarbazar Municipality" },
          { name: "Dordi Rural Municipality" },
          { name: "Dudhpokhari Rural Municipality" },
          { name: "Kwholasothar Rural Municipality" },
          { name: "Marsyangdi Rural Municipality" },
        ],
      },
      {
        name: "Manang",
        municipalities: [
          { name: "Chame Rural Municipality" },
          { name: "Narpa Bhumi Rural Municipality" },
          { name: "Neshyang Rural Municipality" },
          { name: "Manang Ngisyang Rural Municipality" },
        ],
      },
      {
        name: "Mustang",
        municipalities: [
          { name: "Gharpajhong Rural Municipality" },
          { name: "Lo-Ghekar Damodarkunda Rural Municipality" },
          { name: "Thasang Rural Municipality" },
          { name: "Baragung Muktichhetra Rural Municipality" },
          { name: "Lomanthang Rural Municipality" },
        ],
      },
      {
        name: "Myagdi",
        municipalities: [
          { name: "Beni Municipality" },
          { name: "Annapurna Rural Municipality" },
          { name: "Dhaulagiri Rural Municipality" },
          { name: "Malika Rural Municipality" },
          { name: "Mangala Rural Municipality" },
          { name: "Raghuganga Rural Municipality" },
        ],
      },
      {
        name: "Nawalpur",
        municipalities: [
          { name: "Kawasoti Municipality" },
          { name: "Gaindakot Municipality" },
          { name: "Devchuli Municipality" },
          { name: "Madhyabindu Municipality" },
          { name: "Baudikali Rural Municipality" },
          { name: "Bulingtar Rural Municipality" },
          { name: "Binayi Tribeni Rural Municipality" },
          { name: "Hupsekot Rural Municipality" },
        ],
      },
      {
        name: "Parbat",
        municipalities: [
          { name: "Kushma Municipality" },
          { name: "Phalewas Municipality" },
          { name: "Jaljala Rural Municipality" },
          { name: "Mahashila Rural Municipality" },
          { name: "Paiyun Rural Municipality" },
          { name: "Modi Rural Municipality" },
          { name: "Bihadi Rural Municipality" },
        ],
      },
      {
        name: "Syangja",
        municipalities: [
          { name: "Putalibazar Municipality" },
          { name: "Waling Municipality" },
          { name: "Bhirkot Municipality" },
          { name: "Chapakot Municipality" },
          { name: "Galyang Municipality" },
          { name: "Harinas Rural Municipality" },
          { name: "Aandhikhola Rural Municipality" },
          { name: "Kaligandaki Rural Municipality" },
          { name: "Biruwa Rural Municipality" },
          { name: "Arjun Chaupari Rural Municipality" },
          { name: "Phedikhola Rural Municipality" },
        ],
      },
      {
        name: "Tanahun",
        municipalities: [
          { name: "Byas Municipality" },
          { name: "Bhanu Municipality" },
          { name: "Shuklagandaki Municipality" },
          { name: "Bhimad Municipality" },
          { name: "Myagde Rural Municipality" },
          { name: "Rishing Rural Municipality" },
          { name: "Ghiring Rural Municipality" },
          { name: "Devghat Rural Municipality" },
          { name: "Aanbookhaireni Rural Municipality" },
        ],
      },
    ],
  },
  {
    province: "Lumbini Province",
    districts: [
      {
        name: "Kapilvastu",
        municipalities: [
          { name: "Banganga Municipality" },
          { name: "Kapilvastu Municipality" },
          { name: "Buddhabhumi Municipality" },
          { name: "Shivaraj Municipality" },
          { name: "Yashodhara Rural Municipality" },
          { name: "Maharajgunj Municipality" },
          { name: "Mayadevi Rural Municipality" },
          { name: "Suddhodhan Rural Municipality" },
          { name: "Bijaynagar Rural Municipality" },
        ],
      },
      {
        name: "Rupandehi",
        municipalities: [
          { name: "Butwal Sub-Metropolitan City" },
          { name: "Devdaha Municipality" },
          { name: "Lumbini Sanskritik Municipality" },
          { name: "Marchawari Municipality" },
          { name: "Sainamaina Municipality" },
          { name: "Siddharthanagar Municipality" },
          { name: "Siddhartha Highway Rural Municipality" },
          { name: "Tilottama Municipality" },
        ],
      },
      {
        name: "Arghakhanchi",
        municipalities: [
          { name: "Sandhikharka Municipality" },
          { name: "Bhumikasthan Municipality" },
          { name: "Sitganga Municipality" },
          { name: "Painyu Municipality" },
          { name: "Chhatradev Rural Municipality" },
          { name: "Malarani Rural Municipality" },
          { name: "Mantuwa Bardaghat Municipality" },
        ],
      },
      {
        name: "Gulmi",
        municipalities: [
          { name: "Resunga Municipality" },
          { name: "Madane Municipality" },
          { name: "Malika Rural Municipality" },
          { name: "Musikot Municipality" },
          { name: "Dhurkot Rural Municipality" },
          { name: "Isma Rural Municipality" },
          { name: "Kaligandaki Rural Municipality" },
          { name: "Ruru Rural Municipality" },
          { name: "Chandrakot Rural Municipality" },
          { name: "Satyawati Rural Municipality" },
        ],
      },
      {
        name: "Palpa",
        municipalities: [
          { name: "Tansen Municipality" },
          { name: "Rampur Municipality" },
          { name: "Nisdi Rural Municipality" },
          { name: "Rainadevi Chhahara Rural Municipality" },
          { name: "Ribdikot Rural Municipality" },
          { name: "Mathagadi Rural Municipality" },
          { name: "Purbakhola Rural Municipality" },
        ],
      },
      {
        name: "Nawalparasi East",
        municipalities: [
          { name: "Bardaghat Municipality" },
          { name: "Kawasoti Municipality" },
          { name: "Devchuli Municipality" },
          { name: "Gaidakot Municipality" },
          { name: "Binayi Tribeni Rural Municipality" },
          { name: "Hupsekot Rural Municipality" },
          { name: "Sarawal Rural Municipality" },
        ],
      },
      {
        name: "Nawalparasi West",
        municipalities: [
          { name: "Guthi Parsauni Municipality" },
          { name: "Susta Rural Municipality" },
          { name: "Susta Rural Municipality" },
          { name: "Bardaghat Municipality" },
          { name: "Sarawal Rural Municipality" },
          { name: "Kawasoti Municipality" },
          { name: "Gaidakot Municipality" },
          { name: "Binayi Tribeni Rural Municipality" },
        ],
      },
      {
        name: "Pyuthan",
        municipalities: [
          { name: "Pyuthan Municipality" },
          { name: "Sworgadwari Municipality" },
          { name: "Mandavi Rural Municipality" },
          { name: "Naubahini Rural Municipality" },
          { name: "Sarumarani Rural Municipality" },
          { name: "Jhimruk Rural Municipality" },
        ],
      },
      {
        name: "Rolpa",
        municipalities: [
          { name: "Liwang Municipality" },
          { name: "Runtigadhi Rural Municipality" },
          { name: "Gangadev Rural Municipality" },
          { name: "Madi Rural Municipality" },
          { name: "Sunchhahari Rural Municipality" },
          { name: "Sunchhahari Rural Municipality" },
          { name: "Thawang Rural Municipality" },
        ],
      },
      {
        name: "Rukum East",
        municipalities: [
          { name: "Bhume Municipality" },
          { name: "Chaurjahari Municipality" },
          { name: "Sisne Rural Municipality" },
          { name: "Puthauttarganga Rural Municipality" },
          { name: "Aathbiskot Rural Municipality" },
          { name: "Guthichaur Rural Municipality" },
          { name: "Musikot Municipality" },
        ],
      },
      {
        name: "Rukum West",
        municipalities: [
          { name: "Chaurjahari Municipality" },
          { name: "Sisne Rural Municipality" },
          { name: "Puthauttarganga Rural Municipality" },
          { name: "Aathbiskot Rural Municipality" },
          { name: "Guthichaur Rural Municipality" },
          { name: "Musikot Municipality" },
        ],
      },
      {
        name: "Salyan",
        municipalities: [
          { name: "Siddheshwar Municipality" },
          { name: "Bangad Kupinde Municipality" },
          { name: "Kapurkot Municipality" },
          { name: "Bagchaur Municipality" },
          { name: "Dhorchaur Rural Municipality" },
          { name: "Kalimati Rural Municipality" },
          { name: "Triveni Rural Municipality" },
          { name: "Sharada Rural Municipality" },
        ],
      },
      {
        name: "Dang",
        municipalities: [
          { name: "Ghorahi Sub-Metropolitan City" },
          { name: "Tulsipur Sub-Metropolitan City" },
          { name: "Babai Rural Municipality" },
          { name: "Dangisharan Rural Municipality" },
          { name: "Lamahi Municipality" },
          { name: "Rajpur Rural Municipality" },
          { name: "Rapti Rural Municipality" },
          { name: "Gadhawa Rural Municipality" },
          { name: "Rajpur Municipality" },
        ],
      },
    ],
  },
  {
    province: "Karnali Province",
    districts: [
      {
        name: "Dailekh",
        municipalities: [
          { name: "Narayan Municipality" },
          { name: "Aathbis Municipality" },
          { name: "Mahawai Rural Municipality" },
          { name: "Dungeshwor Rural Municipality" },
          { name: "Thantikandh Rural Municipality" },
          { name: "Naumule Rural Municipality" },
          { name: "Bhairabi Rural Municipality" },
          { name: "Gurans Rural Municipality" },
          { name: "Chamunda Bindrasaini Municipality" },
        ],
      },
      {
        name: "Jajarkot",
        municipalities: [
          { name: "Chhedagad Municipality" },
          { name: "Bheri Municipality" },
          { name: "Junichande Rural Municipality" },
          { name: "Shivalaya Rural Municipality" },
          { name: "Tribeni Rural Municipality" },
          { name: "Nalgad Municipality" },
          { name: "Barekot Rural Municipality" },
        ],
      },
      {
        name: "Surkhet",
        municipalities: [
          { name: "Birendranagar Municipality" },
          { name: "Chaukune Rural Municipality" },
          { name: "Gurbhakot Municipality" },
          { name: "Simta Rural Municipality" },
          { name: "Barahatal Rural Municipality" },
          { name: "Panchapuri Municipality" },
          { name: "Lekbesi Municipality" },
          { name: "Lekbesi Municipality" },
          { name: "Bheriganga Municipality" },
        ],
      },
      {
        name: "Salyan",
        municipalities: [
          { name: "Siddheshwar Municipality" },
          { name: "Bangad Kupinde Municipality" },
          { name: "Kapurkot Municipality" },
          { name: "Bagchaur Municipality" },
          { name: "Dhorchaur Rural Municipality" },
          { name: "Kalimati Rural Municipality" },
          { name: "Triveni Rural Municipality" },
          { name: "Sharada Rural Municipality" },
        ],
      },
      {
        name: "Dolpa",
        municipalities: [
          { name: "Tripurasundari Municipality" },
          { name: "Dolpo Buddha Rural Municipality" },
          { name: "Shey Phoksundo Rural Municipality" },
          { name: "Jagadulla Rural Municipality" },
          { name: "Mudkechula Rural Municipality" },
          { name: "Chharka Tangsong Rural Municipality" },
          { name: "Thuli Bheri Municipality" },
        ],
      },
      {
        name: "Humla",
        municipalities: [
          { name: "Simkot Rural Municipality" },
          { name: "Namkha Rural Municipality" },
          { name: "Kharpunath Municipality" },
          { name: "Sarkegad Rural Municipality" },
          { name: "Chankheli Rural Municipality" },
          { name: "Adanchuli Rural Municipality" },
        ],
      },
      {
        name: "Jumla",
        municipalities: [
          { name: "Chandannath Municipality" },
          { name: "Tila Rural Municipality" },
          { name: "Hima Rural Municipality" },
          { name: "Guthichaur Rural Municipality" },
          { name: "Kanakasundari Rural Municipality" },
        ],
      },
      {
        name: "Kalikot",
        municipalities: [
          { name: "Khandachakra Municipality" },
          { name: "Pachaljharana Rural Municipality" },
          { name: "Mahawai Rural Municipality" },
          { name: "Sanni Tribeni Rural Municipality" },
          { name: "Raskot Municipality" },
          { name: "Tila Rural Municipality" },
          { name: "Naraharinath Rural Municipality" },
          { name: "Kali Gandaki Rural Municipality" },
        ],
      },
      {
        name: "Mugu",
        municipalities: [
          { name: "Chhayanath Rara Municipality" },
          { name: "Mugum Karmarong Rural Municipality" },
          { name: "Soru Rural Municipality" },
          { name: "Khatyad Rural Municipality" },
          { name: "Mugum Rural Municipality" },
          { name: "Khatyad Rural Municipality" },
        ],
      },
    ],
  },
  {
    province: "Sudurpashchim Province",
    districts: [
      {
        name: "Achham",
        municipalities: [
          { name: "Mangalsen Municipality" },
          { name: "Kamalbazar Municipality" },
          { name: "Sanphebagar Municipality" },
          { name: "Panchadewal Binayak Municipality" },
          { name: "Bannigadhi Jayagadh Rural Municipality" },
          { name: "Ramaroshan Rural Municipality" },
          { name: "Chaurpati Rural Municipality" },
          { name: "Dhakari Rural Municipality" },
          { name: "Turmakhand Rural Municipality" },
          { name: "	Mellekh Rural Municipality" },
        ],
      },
      {
        name: "Baitadi",
        municipalities: [
          { name: "Dasharathchand Municipality" },
          { name: "Patan Municipality" },
          { name: "Melauli Municipality" },
          { name: "Purchaudi Municipality" },
          { name: "Sunarya Rural Municipality" },
          { name: "Sigas Rural Municipality" },
          { name: "Shivanath Rural Municipality" },
          { name: "Pancheshwor Rural Municipality" },
          { name: "Dogdakedar Rural Municipality" },
          { name: "Dilasaini Rural Municipality" },
        ],
      },
      {
        name: "Bajhang",
        municipalities: [
          { name: "Jaya Prithvi Municipality" },
          { name: "Bungal Municipality" },
          { name: "Talkot Rural Municipality" },
          { name: "Masta Rural Municipality" },
          { name: "Khaptadchhanna Rural Municipality" },
          { name: "Thalara Rural Municipality" },
          { name: "Bitthadchir Rural Municipality" },
          { name: "Surma Rural Municipality" },
          { name: "Chhabis Pathibhera Rural Municipality" },
          { name: "Durgathali Rural Municipality" },
          { name: "Kedarsyu Rural Municipality" },
          { name: "Saipal Rural Municipality" },
        ],
      },
      {
        name: "Bajura",
        municipalities: [
          { name: "Badimalika Municipality" },
          { name: "Triveni Municipality" },
          { name: "Budhiganga Municipality" },
          { name: "Budhinanda Municipality" },
          { name: "Gaumul Rural Municipality" },
          { name: "Jagnnath Rural Municipality" },
          { name: "Swamikartik Khapar Rural Municipality" },
          { name: "Chhededaha Rural Municipality" },
          { name: "Himali Rural Municipality" },
        ],
      },
      {
        name: "Darchula",
        municipalities: [
          { name: "Malikarjun Municipality" },
          { name: "Apihimal Rural Municipality" },
          { name: "Duhun Rural Municipality" },
          { name: "Mahakali Municipality" },
          { name: "Naugadh Rural Municipality" },
          { name: "Shailyashikhar Municipality" },
          { name: "	Marma Rural Municipality" },
          { name: "Lekam Rural Municipality" },
          { name: "Vyans Rural Municipality" },
        ],
      },
      {
        name: "Doti",
        municipalities: [
          { name: "Dipayal Silgadhi Municipality" },
          { name: "Shikhar Municipality" },
          { name: "Purbichauki Rural Municipality" },
          { name: "Badikedar Rural Municipality" },
          { name: "Jorayal Rural Municipality" },
          { name: "Sayal Rural Municipality" },
          { name: "Aadarsha Rural Municipality" },
          { name: "Dr. K. I. Singh Rural Municipality" },
          { name: "Bogatan Rural Municipality" },
        ],
      },
      {
        name: "Kailali",
        municipalities: [
          { name: "Dhangadhi Sub-Metropolitan City" },
          { name: "Lamki Chuha Municipality" },
          { name: "Tikapur Municipality" },
          { name: "Ghodaghodi Municipality" },
          { name: "Bhajani Municipality" },
          { name: "Godawari Municipality" },
          { name: "Gauriganga Municipality" },
          { name: "Janaki Rural Municipality" },
          { name: "Bardagoriya Rural Municipality" },
          { name: "Mohanyal Rural Municipality" },
          { name: "Kailari Rural Municipality" },
          { name: "Joshipur Rural Municipality" },
          { name: "Chure Rural Municipality" },
        ],
      },
      {
        name: "Kanchanpur",
        municipalities: [
          { name: "Bhimdatta Municipality" },
          { name: "Mahakali Municipality" },
          { name: "Shuklaphanta Municipality" },
          { name: "Bedkot Municipality" },
          { name: "Beldandi Rural Municipality" },
          { name: "Belauri Municipality" },
          { name: "Krishnapur Municipality" },
          { name: "Laljhadi Rural Municipality" },
          { name: "Punarbas Municipality" },
        ],
      },
      {
        name: "Dadeldhura",
        municipalities: [
          { name: "Amargadhi municipality" },
          { name: "Parshuram municipality" },
          { name: "Aalitaal Rural Municipality" },
          { name: "Bhageshwar Rural Municipality" },
          { name: "Navadurga Rural Municipality" },
          { name: "Ajaymeru Rural Municipality" },
          { name: "Ganyapadhura Rural Municipality" },
        ],
      },
    ],
  },
];

export default Nepal;
